// <auto-generated />
using System;
using DominosStockOrder.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DominosStockOrder.Server.Migrations
{
    [DbContext(typeof(StockOrderContext))]
    [Migration("20240213103739_Added-ItemAverages-Model")]
    partial class AddedItemAveragesModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DominosStockOrder.Server.Models.InventoryItem", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<float>("PackSize")
                        .HasColumnType("REAL");

                    b.Property<string>("PortalItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("DominosStockOrder.Server.Models.ItemAverages", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekEnding")
                        .HasColumnType("TEXT");

                    b.Property<float>("FoodTheo")
                        .HasColumnType("REAL");

                    b.HasKey("ItemCode", "WeekEnding");

                    b.ToTable("ItemAverages");
                });

            modelBuilder.Entity("DominosStockOrder.Server.Models.ItemAverages", b =>
                {
                    b.HasOne("DominosStockOrder.Server.Models.InventoryItem", "Item")
                        .WithMany("FoodTheoAverages")
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DominosStockOrder.Server.Models.InventoryItem", b =>
                {
                    b.Navigation("FoodTheoAverages");
                });
#pragma warning restore 612, 618
        }
    }
}
