// <auto-generated />
using System;
using DominosStockOrder.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DominosStockOrder.Server.Migrations
{
    [DbContext(typeof(StockOrderContext))]
    partial class StockOrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DominosStockOrder.Server.Models.InventoryItem", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<float>("PackSize")
                        .HasColumnType("REAL");

                    b.Property<string>("PortalItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockOrderPortalOrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("StockOrderPortalOrderId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("DominosStockOrder.Server.Models.StockOrder", b =>
                {
                    b.Property<string>("PortalOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PortalOrderId");

                    b.ToTable("StockOrders");
                });

            modelBuilder.Entity("DominosStockOrder.Server.Models.InventoryItem", b =>
                {
                    b.HasOne("DominosStockOrder.Server.Models.StockOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("StockOrderPortalOrderId");
                });

            modelBuilder.Entity("DominosStockOrder.Server.Models.StockOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
